INSERT INTO `yingwenerge` VALUES ('Abc - 英文字母歌.mp3');
INSERT INTO `yingwenerge` VALUES ('网络歌手 - 儿歌大全英文食物水果名称.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - 1.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - 11.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - 16.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - 2.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - 20.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - 22.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - 24.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - 26.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - 3.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - 33.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - 37.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - 38.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - 6.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - 7.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - 8.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - 9.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - A For Apple B For Boy.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - A Hunting We Will Go.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - A.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - All The Pretty Little Horses.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - All Through The Night.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - Alphabet Song.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - Am.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - Angels.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - Apple.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - Au.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - Baa Baa Black Sheep.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - Balloons.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - Barbie Girl.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - Betty.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - Billy Boy.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - Blow The Man Down.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - Boy Girl.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - Bridge.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - Clap Your Hands.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - Colour Song.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - Colours.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - Deck The Halls.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - Did You Ever See A Lassie.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - Ding Dong Bell.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - Dixie.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - Do Re Me.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - Do Re Mi.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - Doctor.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - Et.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - Everybody Jump.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - F.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - Fishes Fishes Where Are You.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - Five Little Ducks - 五只小鸭.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - Five Little Ducks.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - 企鹅舞.mp3');
INSERT INTO `yingwenerge` VALUES ('英文儿歌 - 生日快乐歌happy Birthday To You.mp3');
