INSERT INTO `yingwengushi` VALUES ('clare and the fair-克莱尔和游乐园.mp3');
INSERT INTO `yingwengushi` VALUES ('Class Teddy Bear（班级里的玩具熊）.mp3');
INSERT INTO `yingwengushi` VALUES ('Hairy Harry（长毛哈里）.mp3');
INSERT INTO `yingwengushi` VALUES ('the deer and the earwig-小鹿和蠼螋.mp3');
INSERT INTO `yingwengushi` VALUES ('一千零一夜01.mp3');
INSERT INTO `yingwengushi` VALUES ('一千零一夜02.mp3');
INSERT INTO `yingwengushi` VALUES ('不称职的骑士The Wrong Kind of Knight.mp3');
INSERT INTO `yingwengushi` VALUES ('乌斯曼的书-Usman ’s Books.mp3');
INSERT INTO `yingwengushi` VALUES ('今天没有牛奶No Milk Today.mp3');
INSERT INTO `yingwengushi` VALUES ('仙笛神童1.mp3');
INSERT INTO `yingwengushi` VALUES ('仙笛神童2.mp3');
INSERT INTO `yingwengushi` VALUES ('伊索寓言1.mp3');
INSERT INTO `yingwengushi` VALUES ('伊索寓言2.mp3');
INSERT INTO `yingwengushi` VALUES ('伊索寓言3.mp3');
INSERT INTO `yingwengushi` VALUES ('伊索寓言4.mp3');
INSERT INTO `yingwengushi` VALUES ('伯特，你去哪儿了-Where Were You Bert.mp3');
INSERT INTO `yingwengushi` VALUES ('侦探斯尼夫.mp3');
INSERT INTO `yingwengushi` VALUES ('修修小姐.mp3');
INSERT INTO `yingwengushi` VALUES ('兽医葆拉-Paula the Vet.mp3');
INSERT INTO `yingwengushi` VALUES ('勒罗伊 Leroy.mp3');
INSERT INTO `yingwengushi` VALUES ('化身博士1.mp3');
INSERT INTO `yingwengushi` VALUES ('化身博士2.mp3');
INSERT INTO `yingwengushi` VALUES ('匹诺曹1.mp3');
INSERT INTO `yingwengushi` VALUES ('匹诺曹2.mp3');
INSERT INTO `yingwengushi` VALUES ('十二生肖的故事（英文版）.mp3');
INSERT INTO `yingwengushi` VALUES ('哈克贝里-芬历险记1.mp3');
INSERT INTO `yingwengushi` VALUES ('哈克贝里-芬历险记2.mp3');
INSERT INTO `yingwengushi` VALUES ('哈里和拉里.mp3');
INSERT INTO `yingwengushi` VALUES ('唠叨唠叨唠叨！Moan，Moan，Moan！.mp3');
INSERT INTO `yingwengushi` VALUES ('噼里啪啦，吧唧吧唧Splash and Squelch.mp3');
INSERT INTO `yingwengushi` VALUES ('外研社丽声拼读故事会第6级：Tara’s Party-塔拉的派对.mp3');
INSERT INTO `yingwengushi` VALUES ('奇怪的宠物 The Odd Pet.mp3');
INSERT INTO `yingwengushi` VALUES ('奇怪的布朗一家The Upside-down Browns.mp3');
INSERT INTO `yingwengushi` VALUES ('奥赛罗1.mp3');
INSERT INTO `yingwengushi` VALUES ('奥赛罗2.mp3');
INSERT INTO `yingwengushi` VALUES ('奶奶生气了Gran is Cross.mp3');
INSERT INTO `yingwengushi` VALUES ('威尼斯商人1.mp3');
INSERT INTO `yingwengushi` VALUES ('威尼斯商人2.mp3');
INSERT INTO `yingwengushi` VALUES ('安妮娜王后的宴会Queen Anneena’s Feast.mp3');
INSERT INTO `yingwengushi` VALUES ('安妮的日记01.mp3');
INSERT INTO `yingwengushi` VALUES ('安妮的日记02.mp3');
INSERT INTO `yingwengushi` VALUES ('小小鸟.mp3');
INSERT INTO `yingwengushi` VALUES ('小屁孩二三事.mp3');
INSERT INTO `yingwengushi` VALUES ('小屁孩儿咯咯笑.mp3');
INSERT INTO `yingwengushi` VALUES ('小心脚下兔子先生.mp3');
INSERT INTO `yingwengushi` VALUES ('小王子02.mp3');
INSERT INTO `yingwengushi` VALUES ('小虫鲍勃- Bob Bug.mp3');
INSERT INTO `yingwengushi` VALUES ('小锡兵1.mp3');
INSERT INTO `yingwengushi` VALUES ('希腊、罗马神话故事1.mp3');
INSERT INTO `yingwengushi` VALUES ('希腊、罗马神话故事2.mp3');
INSERT INTO `yingwengushi` VALUES ('帮倒忙.mp3');
INSERT INTO `yingwengushi` VALUES ('戏剧《灰姑娘》The Cinderella Play.mp3');
INSERT INTO `yingwengushi` VALUES ('捡来的小猫 New Kitten.mp3');
INSERT INTO `yingwengushi` VALUES ('斯派克说Spike  Says.mp3');
INSERT INTO `yingwengushi` VALUES ('李尔王1.mp3');
INSERT INTO `yingwengushi` VALUES ('李尔王2.mp3');
INSERT INTO `yingwengushi` VALUES ('杰克与豆秆1.mp3');
INSERT INTO `yingwengushi` VALUES ('杰克与豆秆2.mp3');
INSERT INTO `yingwengushi` VALUES ('杰克和巨人-Jack and the Giants.mp3');
INSERT INTO `yingwengushi` VALUES ('格列佛游记1.mp3');
INSERT INTO `yingwengushi` VALUES ('格列佛游记2.mp3');
INSERT INTO `yingwengushi` VALUES ('汉赛尔和格莱特1.mp3');
INSERT INTO `yingwengushi` VALUES ('汉赛尔和格莱特2.mp3');
INSERT INTO `yingwengushi` VALUES ('汤姆索亚历险记1.mp3');
INSERT INTO `yingwengushi` VALUES ('汤姆索亚历险记2.mp3');
INSERT INTO `yingwengushi` VALUES ('消防员斯莫奇.mp3');
INSERT INTO `yingwengushi` VALUES ('爱唱歌的爸爸Singing Dad.mp3');
INSERT INTO `yingwengushi` VALUES ('爱探险的朵拉(第二季)01-The Big Storm.mp3');
INSERT INTO `yingwengushi` VALUES ('爱探险的朵拉26-Quack！ Quack！.mp3');
INSERT INTO `yingwengushi` VALUES ('爱探险的朵拉（第一季）01-The Legend of the Big Red Chicken.mp3');
INSERT INTO `yingwengushi` VALUES ('爱探险的朵拉（第一季）27-The Lost City.mp3');
INSERT INTO `yingwengushi` VALUES ('犹太法典01.mp3');
INSERT INTO `yingwengushi` VALUES ('犹太法典02.mp3');
INSERT INTO `yingwengushi` VALUES ('王子与乞丐1.mp3');
INSERT INTO `yingwengushi` VALUES ('王子与乞丐2.mp3');
INSERT INTO `yingwengushi` VALUES ('白雪公主和友情魔法1.mp3');
INSERT INTO `yingwengushi` VALUES ('白雪公主和友情魔法2.mp3');
INSERT INTO `yingwengushi` VALUES ('睡美人1.mp3');
INSERT INTO `yingwengushi` VALUES ('睡美人2.mp3');
INSERT INTO `yingwengushi` VALUES ('破烂火箭The Scrap Rocket.mp3');
INSERT INTO `yingwengushi` VALUES ('科学怪人1.mp3');
INSERT INTO `yingwengushi` VALUES ('科学怪人2.mp3');
INSERT INTO `yingwengushi` VALUES ('罗宾汉1.mp3');
INSERT INTO `yingwengushi` VALUES ('罗宾汉2.mp3');
INSERT INTO `yingwengushi` VALUES ('罗密欧与朱丽叶1.mp3');
INSERT INTO `yingwengushi` VALUES ('罗密欧与朱丽叶2.mp3');
INSERT INTO `yingwengushi` VALUES ('美女与野兽-1.mp3');
INSERT INTO `yingwengushi` VALUES ('美女与野兽2.mp3');
INSERT INTO `yingwengushi` VALUES ('老人与海01.mp3');
INSERT INTO `yingwengushi` VALUES ('老人与海02.mp3');
INSERT INTO `yingwengushi` VALUES ('艾丽丝漫游奇境记1.mp3');
INSERT INTO `yingwengushi` VALUES ('艾丽丝漫游奇境记2.mp3');
INSERT INTO `yingwengushi` VALUES ('蛇和鸭爸爸The Snake and the Drake.mp3');
INSERT INTO `yingwengushi` VALUES ('蝌蚪Tadpoles.mp3');
INSERT INTO `yingwengushi` VALUES ('袋鼠小休-Sue Kangaroo.mp3');
INSERT INTO `yingwengushi` VALUES ('象鼻和臭鼬The Trunk and the Skunk.mp3');
INSERT INTO `yingwengushi` VALUES ('购物单The Shopping List.mp3');
INSERT INTO `yingwengushi` VALUES ('足球大赛The Big Match.mp3');
INSERT INTO `yingwengushi` VALUES ('这和那This and That.mp3');
INSERT INTO `yingwengushi` VALUES ('金银岛1.mp3');
INSERT INTO `yingwengushi` VALUES ('金银岛2.mp3');
INSERT INTO `yingwengushi` VALUES ('阿拉丁与神灯1.mp3');
INSERT INTO `yingwengushi` VALUES ('阿拉丁与神灯2.mp3');
INSERT INTO `yingwengushi` VALUES ('青蛙王子1.mp3');
INSERT INTO `yingwengushi` VALUES ('青蛙王子2.mp3');
INSERT INTO `yingwengushi` VALUES ('馅饼炮弹.mp3');
INSERT INTO `yingwengushi` VALUES ('鱼和薯条Fish and Chip.mp3');
INSERT INTO `yingwengushi` VALUES ('鲁宾逊漂流记1.mp3');
INSERT INTO `yingwengushi` VALUES ('鲁宾逊漂流记2.mp3');
INSERT INTO `yingwengushi` VALUES ('鸭子医生Doctor Duck.mp3');
INSERT INTO `yingwengushi` VALUES ('麦克白1.mp3');
INSERT INTO `yingwengushi` VALUES ('麦克白2.mp3');
INSERT INTO `yingwengushi` VALUES ('（农夫和孩子们）我的故事袋.mp3');
INSERT INTO `yingwengushi` VALUES ('（朵拉）A Crown for King Juan el Bobo.mp3');
INSERT INTO `yingwengushi` VALUES ('（朵拉）Baby Jaguar.mp3');
INSERT INTO `yingwengushi` VALUES ('（朵拉）Big Sister Dora.mp3');
INSERT INTO `yingwengushi` VALUES ('（朵拉）Boots to the Rescue.mp3');
INSERT INTO `yingwengushi` VALUES ('（朵拉）Catch the Babies.mp3');
INSERT INTO `yingwengushi` VALUES ('（朵拉）Daisy， la Quinceanera.mp3');
INSERT INTO `yingwengushi` VALUES ('（朵拉）Dance to the Rescue.mp3');
INSERT INTO `yingwengushi` VALUES ('（朵拉）Dora and Diego to the Rescue.mp3');
INSERT INTO `yingwengushi` VALUES ('（朵拉）Dora World Adventure.mp3');
INSERT INTO `yingwengushi` VALUES ('（朵拉）Fairytale Adventure.mp3');
INSERT INTO `yingwengushi` VALUES ('（朵拉）First Trip.mp3');
INSERT INTO `yingwengushi` VALUES ('（朵拉）Got a Puppy.mp3');
INSERT INTO `yingwengushi` VALUES ('（朵拉）La Maestra de Musica.mp3');
INSERT INTO `yingwengushi` VALUES ('（朵拉）Save Diego Animal Adventures.mp3');
INSERT INTO `yingwengushi` VALUES ('（朵拉）Star Mountain.mp3');
INSERT INTO `yingwengushi` VALUES ('（朵拉）Starcatching Adventure.mp3');
INSERT INTO `yingwengushi` VALUES ('（朵拉）Super Babies.mp3');
INSERT INTO `yingwengushi` VALUES ('（朵拉）Super Spies 2 The Swiping Machine.mp3');
INSERT INTO `yingwengushi` VALUES ('（朵拉）Swiper The Explorer.mp3');
INSERT INTO `yingwengushi` VALUES ('（朵拉）The Mixed-Up Seasons.mp3');
INSERT INTO `yingwengushi` VALUES ('（朵拉）Were A Team.mp3');
INSERT INTO `yingwengushi` VALUES ('（狼来了）双语小故事.mp3');
INSERT INTO `yingwengushi` VALUES ('（生金蛋的鹅）双语小故事.mp3');
INSERT INTO `yingwengushi` VALUES ('（蚂蚁和蚂蚱）双语小故事.mp3');
