INSERT INTO `zaojiaoyingyu` VALUES ('001家庭成员称呼.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('002头部五官名称.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('003身体各部位名称.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('004礼貌问候语.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('005数字.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('006二十六个英文字母.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('007宝莉烧开水.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('008春夏秋冬四季.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('009十二个月.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('010天气用语.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('011表情用语名称.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('012动作名称.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('013穿戴用品名称.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('014文具用品名称.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('015体育用品名称.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('016星期歌.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('017我爱我家.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('018食物名称.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('019家用电器.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('020卫生用品名称.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('021餐具名称.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('022水果名称.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('023家禽家畜名称.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('024海洋动物名称.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('025宝莉小姐有个洋娃娃.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('026自然景物名称.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('027颜色名称.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('028天文地理名称.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('029昆虫世界.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('030方位名称.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('031鸟类天地.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('032生日快乐歌.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('033建筑名称.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('034交通工具名称.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('035社会职业名称.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('036公园动物名称.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('037公园景物名称.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('038卡通人物.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('039哆来咪.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('040平安夜.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('041铃儿响叮当.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('042咩咩黑羊儿.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('043泥娃娃.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('044三双小猫.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('045闪闪小星星.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('046睡吧小宝宝.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('047形状名称.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('048日期名称.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('049动物园.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('050儿童称呼.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('051公园工具.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('052花草树木.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('053家庭用品.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('054日月星空.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('055上下大小.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('056自然天气.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('057自然现象.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('058国际音标辅音-爆破音.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('059国际音标辅音-摩擦音.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('060国际音标辅音-鼻音.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('061国际音标辅音-舌侧音.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('062国际音标辅音-破檫音.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('063国际音标辅音-半元音.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('064国际音标元音-单元音.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('065国际音标元音-双元音.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('066What A Wonderful world.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('067Song Of ABC.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('068Head,Shoulders Knees & Toes.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('069Mary Had A Little Lamb.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('070Michael,Row Your Boat.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('071Twinkle Little Star.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('072London Bridge Is Falling Down.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('073Old McDonald Had A Farm.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('074Baa Baa Black Sheep.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('075Polly Put The Kettle On.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('076Old Black Joe.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('077One Two Three Four Five.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('078To Market To Market.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('079Finger Song.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('080An Apple.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('081 Little Indians.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('082When The Saints Go Marching In.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('083Music Box Dancer.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('084My Puppy.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('085Lightly Row.mp3');
INSERT INTO `zaojiaoyingyu` VALUES ('086Humpty Dumpty.mp3');
